/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author Catito
 */
public class Interfaz extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
        this.setLocationRelativeTo(null);
        
    }
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/LOGO.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2icono = new javax.swing.JLabel();
        jLabel2usuario = new javax.swing.JLabel();
        jLabel2contraseña = new javax.swing.JLabel();
        txtuser = new javax.swing.JTextField();
        contra = new javax.swing.JPasswordField();
        jButton2sesion = new javax.swing.JButton();
        jLabel1fondo = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(0, 153, 153));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("X");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, 30, 30));

        jLabel2icono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cybercandado.PNG"))); // NOI18N
        jLabel2icono.setText("jLabel2");
        getContentPane().add(jLabel2icono, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 390, 360));

        jLabel2usuario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2usuario.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2usuario.setText("USUARIO");
        getContentPane().add(jLabel2usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, -1, -1));

        jLabel2contraseña.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2contraseña.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2contraseña.setText("CONTRASEÑA");
        getContentPane().add(jLabel2contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, -1, -1));

        txtuser.setBackground(new java.awt.Color(0, 102, 102));
        txtuser.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtuser.setForeground(new java.awt.Color(255, 255, 255));
        txtuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtuserActionPerformed(evt);
            }
        });
        getContentPane().add(txtuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 360, 220, 30));

        contra.setBackground(new java.awt.Color(0, 102, 102));
        contra.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        contra.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(contra, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 410, 220, 30));

        jButton2sesion.setBackground(new java.awt.Color(0, 102, 102));
        jButton2sesion.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton2sesion.setForeground(new java.awt.Color(255, 255, 255));
        jButton2sesion.setText("INICIAR SESION");
        jButton2sesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2sesionMouseClicked(evt);
            }
        });
        jButton2sesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2sesionActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2sesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 460, -1, -1));

        jLabel1fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/interfazas completa .jpeg"))); // NOI18N
        getContentPane().add(jLabel1fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 564));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtuserActionPerformed
        
    }//GEN-LAST:event_txtuserActionPerformed

    private void jButton2sesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2sesionActionPerformed
        
    }//GEN-LAST:event_jButton2sesionActionPerformed

    private void jButton2sesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2sesionMouseClicked
        String usuario="Administrador"; 
        String contrasena="CTJ181924";
        
        
        String Pass = new String(contra.getPassword());
        if(txtuser.getText().equals(usuario)&& Pass.equals(contrasena)){
            menupri mp = new menupri ();
            mp.setVisible(true);
            dispose();
        }else {
            JOptionPane.showMessageDialog(this,"usurio o contraseña incorrectos ");
        }
        
    }//GEN-LAST:event_jButton2sesionMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField contra;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2sesion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel1fondo;
    private javax.swing.JLabel jLabel2contraseña;
    private javax.swing.JLabel jLabel2icono;
    private javax.swing.JLabel jLabel2usuario;
    private javax.swing.JTextField txtuser;
    // End of variables declaration//GEN-END:variables
}
