/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import java.awt.Image;
import java.awt.Toolkit;

/**
 *
 * @author Catito
 */
public class Invertario extends javax.swing.JFrame {

    /**
     * Creates new form Invertario
     */
    public Invertario() {
        initComponents();
     this.setLocationRelativeTo(null);
        
    }
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/LOGO.png"));
        return retValue;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1tabladedatos = new javax.swing.JTable();
        jButton1regreamenu = new javax.swing.JButton();
        jButton1salir = new javax.swing.JButton();
        jButton1buscarpro = new javax.swing.JButton();
        jTextField1datos = new javax.swing.JTextField();
        jLabel1titulo = new javax.swing.JLabel();
        jLabel1fondo = new javax.swing.JLabel();
        jLabel1fondo2 = new javax.swing.JLabel();
        jLabel1fondo3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setBackground(new java.awt.Color(204, 204, 204));
        jScrollPane1.setForeground(new java.awt.Color(0, 0, 0));

        jTable1tabladedatos.setBackground(new java.awt.Color(0, 102, 102));
        jTable1tabladedatos.setForeground(new java.awt.Color(0, 0, 0));
        jTable1tabladedatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1tabladedatos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 930, 420));

        jButton1regreamenu.setBackground(new java.awt.Color(255, 255, 255));
        jButton1regreamenu.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jButton1regreamenu.setForeground(new java.awt.Color(0, 0, 0));
        jButton1regreamenu.setText("REGRESAR");
        jButton1regreamenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1regreamenuActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1regreamenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 20));

        jButton1salir.setBackground(new java.awt.Color(255, 255, 255));
        jButton1salir.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jButton1salir.setForeground(new java.awt.Color(0, 0, 0));
        jButton1salir.setText("X");
        jButton1salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1salirActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 10, -1, 20));

        jButton1buscarpro.setBackground(new java.awt.Color(0, 255, 0));
        jButton1buscarpro.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jButton1buscarpro.setForeground(new java.awt.Color(255, 255, 255));
        jButton1buscarpro.setText("BUSCAR PRODUCTO");
        jButton1buscarpro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1buscarproActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1buscarpro, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 110, 220, 30));

        jTextField1datos.setBackground(new java.awt.Color(0, 102, 102));
        jTextField1datos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTextField1datos.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jTextField1datos, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 770, 40));

        jLabel1titulo.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel1titulo.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1titulo.setText("INVENTARIO");
        getContentPane().add(jLabel1titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, -1, -1));

        jLabel1fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/facturacion.jpeg"))); // NOI18N
        getContentPane().add(jLabel1fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 620));

        jLabel1fondo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/facturacion.jpeg"))); // NOI18N
        getContentPane().add(jLabel1fondo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 0, 360, 620));

        jLabel1fondo3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/facturacion.jpeg"))); // NOI18N
        getContentPane().add(jLabel1fondo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, 360, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1buscarproActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1buscarproActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1buscarproActionPerformed

    private void jButton1salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1salirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1salirActionPerformed

    private void jButton1regreamenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1regreamenuActionPerformed
        this.setVisible(false);
        menupri c= new menupri();
        c.setVisible(true);
    }//GEN-LAST:event_jButton1regreamenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Invertario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Invertario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Invertario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Invertario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Invertario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1buscarpro;
    private javax.swing.JButton jButton1regreamenu;
    private javax.swing.JButton jButton1salir;
    private javax.swing.JLabel jLabel1fondo;
    private javax.swing.JLabel jLabel1fondo2;
    private javax.swing.JLabel jLabel1fondo3;
    private javax.swing.JLabel jLabel1titulo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1tabladedatos;
    private javax.swing.JTextField jTextField1datos;
    // End of variables declaration//GEN-END:variables
}
