/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import java.awt.Image;
import java.awt.Toolkit;

/**
 *
 * @author Catito
 */
public class menupri extends javax.swing.JFrame {

    /**
     * Creates new form menupri
     */
    public menupri() {
        initComponents();
    this.setLocationRelativeTo(null);
        
    }
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/LOGO.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1BIENVENIDO = new javax.swing.JLabel();
        jButton1facturacionyclie = new javax.swing.JButton();
        jButton1invetario = new javax.swing.JButton();
        jButton1comprasyprove = new javax.swing.JButton();
        DIBUJITO = new javax.swing.JLabel();
        jButton1salir = new javax.swing.JButton();
        jLabel1fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1BIENVENIDO.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        jLabel1BIENVENIDO.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1BIENVENIDO.setText("BIENVENIDO");
        getContentPane().add(jLabel1BIENVENIDO, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, -1, -1));

        jButton1facturacionyclie.setBackground(new java.awt.Color(0, 102, 102));
        jButton1facturacionyclie.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jButton1facturacionyclie.setForeground(new java.awt.Color(255, 255, 255));
        jButton1facturacionyclie.setText("FACTURACION   Y  CLIENTES ");
        jButton1facturacionyclie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1facturacionyclieActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1facturacionyclie, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 300, 50));

        jButton1invetario.setBackground(new java.awt.Color(0, 102, 102));
        jButton1invetario.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jButton1invetario.setForeground(new java.awt.Color(255, 255, 255));
        jButton1invetario.setText("INVENTARIO");
        jButton1invetario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1invetarioActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1invetario, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 300, 50));

        jButton1comprasyprove.setBackground(new java.awt.Color(0, 102, 102));
        jButton1comprasyprove.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jButton1comprasyprove.setForeground(new java.awt.Color(255, 255, 255));
        jButton1comprasyprove.setText("COMPRAS Y PROVEEDORES");
        jButton1comprasyprove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1comprasyproveActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1comprasyprove, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 360, 300, 50));

        DIBUJITO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/personitas.png"))); // NOI18N
        getContentPane().add(DIBUJITO, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 450, 150, 80));

        jButton1salir.setBackground(new java.awt.Color(255, 255, 255));
        jButton1salir.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jButton1salir.setForeground(new java.awt.Color(0, 0, 0));
        jButton1salir.setText("X");
        jButton1salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1salirActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 10, -1, 20));

        jLabel1fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/menu.jpeg"))); // NOI18N
        getContentPane().add(jLabel1fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1comprasyproveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1comprasyproveActionPerformed
       this.setVisible(false);
        comyprove c= new comyprove();
        c.setVisible(true);
    }//GEN-LAST:event_jButton1comprasyproveActionPerformed

    private void jButton1salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1salirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1salirActionPerformed

    private void jButton1facturacionyclieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1facturacionyclieActionPerformed
         this.setVisible(false);
        facturasyclientes c= new facturasyclientes();
        c.setVisible(true);
    }//GEN-LAST:event_jButton1facturacionyclieActionPerformed

    private void jButton1invetarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1invetarioActionPerformed
         this.setVisible(false);
        Invertario c= new Invertario();
        c.setVisible(true);
    }//GEN-LAST:event_jButton1invetarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menupri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menupri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menupri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menupri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menupri().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DIBUJITO;
    private javax.swing.JButton jButton1comprasyprove;
    private javax.swing.JButton jButton1facturacionyclie;
    private javax.swing.JButton jButton1invetario;
    private javax.swing.JButton jButton1salir;
    private javax.swing.JLabel jLabel1BIENVENIDO;
    private javax.swing.JLabel jLabel1fondo;
    // End of variables declaration//GEN-END:variables
}
